### Site metadata ###
show_downloads: true
title: Pankil Shah CV + Blog 
description: "My blog of experiences around DevOps"

### Build settings ###

url: https://pankils.github.io
baseurl: /aboutMyZ
repository: pankils/aboutMyZ

theme: jekyll-theme-midnight

plugins:
  - jekyll-feed
  - jekyll-sitemap

short_date: "%b %-d, %Y"

google_analytics:   

# TODO: Configure admin to not pick up static fonts.
# ...

# defaults:
#   - scope:
#       path: "_posts"
#     values:
#       layout: "post"
#   - scope:
#       path: ""
#     values:
#       layout: "page"

exclude:
  - vendor/
  - LICENSE
  - Makefile
  - README.md
  - Gemfile
